name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wasm toolchain
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose --release --target wasm32-unknown-unknown
    - name: Copy .wasm to root
      run: cp target/wasm32-unknown-unknown/release/nemu.wasm nemu.wasm
